[tool.mypy]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true
# mypy_path = "./.venv"



[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.format]
skip-magic-trailing-comma = true
